### ISSUE TITLE
新手求助

### ISSUE THREAD

**Issue by LePingKYXK** [Haojen/hexo-theme-Claudia#13]
1)
我 clone 了您的主题到本地 myusername.github.io/blog/themes/ 路径下，我改了个名字为 Claudia
，对相应的内容按照您写的步骤进行修改，然后 git add .  接着 git commit -m "update theme"，但是用 git push 命令同步到我的 GitHub 网络端上，却发现如下的问题。
`$ git clone https://github.com/Haojen/hexo-theme-Claudia themes/Claudia`
`$ git add .`
`$ git push`
`remote: Permission to Haojen/hexo-theme-Claudia.git denied to LePingKYXK.
fatal: unable to access 'https://github.com/Haojen/hexo-theme-Claudia/': The requested URL returned error: 403`

我同时发现，我的 https://github.com/LePingKYXK/LePingKYXK.github.io/tree/master/blog/themes 目录下有一个 Claudia 文件夹，却无法打开…… 不知道是不是应该删掉原始的（也就是您的 theme 文件夹中的） .git 和 .gitignore 文件？然后再 git push？

2)
> menu:
>   Home: / #页面所在的路径

请问这里“页面所在的路径 ” 是指的什么？ 本地计算机上的路径？ 还是 GitHub 上对应的 username.github.io/blog/ 路径？

**Comment by DraceWang** [comment]
@LePingKYXK 
你好，你的第一个问题建议你先去了解下git的工作原理，git push是推送到远程代码仓库，你一定没有原作者的代码仓库权限，所以肯定不能成功，并且，clone代码的目的是使用和修改，改动后需要有什么希望作者合并的应该发起pullrequest。至于这个问题，我没看明白，暂时不能给你什么帮助。

你的第二个问题，Home是显示在你博客右侧导航的文字，冒号后面的路劲表示的是你通过hexo生成的博客网站的根目录地址，一般你不需要修改
