### ISSUE TITLE
希望能优化下代码渲染的效果

### ISSUE THREAD

**Issue by Liam8** [Haojen/hexo-theme-Claudia#16]
这是demo里面的效果😓
![image](https://user-images.githubusercontent.com/14144698/35767624-f265beee-092a-11e8-8f1d-849872d6a199.png)

**Comment by AverageJoeWang** [comment]
是哇，我感觉这个代码效果好的话应该用的人会很多

**Comment by Haojen** [comment]
@Liam8  I will fix that, on next version, Thank you for your advice
