### ISSUE TITLE
博客加载pdf问题。

### ISSUE THREAD

**Issue by c0k1sh** [Haojen/hexo-theme-Claudia#22]
博客文章插入文章 pdf 只显示连半页都不到。看了半天没看到是哪里的问题。

**Comment by c0k1sh** [comment]
@Haojen Here is the website.[https://best5.club/2018/08/24/PDF%20%E5%8A%A0%E8%BD%BD%E6%B5%8B%E8%AF%95/]
Question：【Normal PDF】It can't be dispalyed completely in your hexo theme.  But in other hexo themes it can be dispalyed normally.

Besides, it seems that there are also some compatibility issues. If it can't be dispalyed normally in google chorme, Maybe you can try opening it  with the edge brower.
![pdf question1](https://user-images.githubusercontent.com/39668851/44640594-1b9a9f80-a9f5-11e8-889e-e7de100ca7fb.png)

Thanks for your reply. Your hexo theme is really beautiful！

**Comment by c0k1sh** [comment]
[PDF只能显示一部分](https://best5.club/2018/08/24/PDF%20加载测试/)

**Comment by c0k1sh** [comment]
没呢，不知道问题在哪
<img width="1611" alt="2018-12-19 11 25 25" src="https://user-images.githubusercontent.com/39668851/50230716-30f26a00-03e8-11e9-8c90-ee966c3c4bfa.png">

**Comment by Haojen** [comment]
@c0k1sh  @littleZhuo 问题已经修复上线，请诸位拉取一下最新的代码

**Comment by littleZhuo** [comment]
@c0k1sh  我拉了最新代码Master分支，重新hexo g;后，还是显示很窄。是我的操作不对么？

**Comment by c0k1sh** [comment]
> @c0k1sh 我拉了最新代码Master分支，重新hexo g;后，还是显示很窄。是我的操作不对么？

@littleZhuo 来个链接呀。你看下那个css那里改过了吗，或者你可以把那个css文件放到本地 删除里面的embed试试。
