### ISSUE TITLE
关于来比力评论系统

### ISSUE THREAD

**Issue by libaolb0629** [Haojen/hexo-theme-Claudia#24]
已经配置好来比力配置系统，然而每次当进去一次可以看到来比力加载完后，再进一次就看不到了。也看不到评论系统了。是主题的问题，还是来比力的问题呢。

**Comment by nilnaijgnid** [comment]
为啥我的根本加载不出来呢

**Comment by fenglh** [comment]
me too

**Comment by Haojen** [comment]
我也有这个问题，之前一直没有人反馈，所以一直以为是我个人的网络环境有关。最近会拿到解决方案给大家，多谢使用和反馈

**Comment by Haojen** [comment]
已经修复 感谢反馈
