### ISSUE TITLE
文章写完后在主页能显示文章但是点击后进入不了，url只有文字名字

### ISSUE THREAD

**Issue by winsydeny** [Haojen/hexo-theme-Claudia#27]
![image](https://user-images.githubusercontent.com/34545949/49686631-23a8c600-fb32-11e8-87d6-e0af482eda6a.png)

![image](https://user-images.githubusercontent.com/34545949/49686646-68346180-fb32-11e8-9064-a7110b460057.png)

**Comment by Haojen** [comment]
已修复，感谢反馈
