### ISSUE TITLE
评论添加无法显示，好像你的演示项目里也没有评论

### ISSUE THREAD

**Issue by earthWo** [Haojen/hexo-theme-Claudia#3]

**Comment by BlankGii** [comment]
你好，我也遇过同样的问题无法解决，然后找到博主的另一份主题，链接如下，是claudia的升级版吧。然后解决了“来必力”评论无法显示的问题。
https://haojen.github.io/2017/05/09/Anisina-%E4%B8%AD%E6%96%87%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B/

**Comment by earthWo** [comment]
我就是从Anisina换过来的，但是好像claudia是升级版，功能也多一些，就是无法添加评论

**Comment by BlankGii** [comment]
哈哈，确实是我搞混了。我猜博主应该还在调试中把。

**Comment by Haojen** [comment]
这段时间工作忙， 等清闲下来了再修复。 预计这个周天可以修了。
多谢两位的反馈。
