### ISSUE TITLE
图片

### ISSUE THREAD

**Issue by LeoAshin** [Haojen/hexo-theme-Claudia#33]
post-cover图能不能自适应啊?
为了缩略图好看要特地去修改分辨率, 结果到移动端又不一样了
小问题. 只是有时候强迫症难受

**Comment by Haojen** [comment]
能不能把移动端上对效果截图贴上来看看？

**Comment by LeoAshin** [comment]
表述错误。 
移动端那个是我说错了。 其实是想说就是非全屏窗口打开的时候的图片显示。
看看图片这块还有优化的空间没，如果没有就算了。

**Comment by Haojen** [comment]
@LeoAshin 感谢反馈，已经修复
