### ISSUE TITLE
代码高亮失败

### ISSUE THREAD

**Issue by HuangZhenyang** [Haojen/hexo-theme-Claudia#35]
已经照着README.md中的要求，将根目录下的highlight那些选项设置成false。
![TIM截图20190730224703](https://user-images.githubusercontent.com/17945092/62139570-2c961400-b31c-11e9-97f4-05b83f3e854b.png)

但是预览时发现代码全乱了。。。

请问您有解决方案吗

**Comment by Haojen** [comment]
@HuangZhenyang 感谢反馈，已经修复
