### ISSUE TITLE
一些文档的建议

### ISSUE THREAD

**Issue by lvfangren** [Haojen/hexo-theme-Claudia#43]
hello，我使用了你的hexo-theme-Claudia主题。但是在使用时发现： 1:中英文文档好像不同步；2:  中文文档中存在一些Markdown语法的小瑕疵（可以的话我会进行pr）；3: 在安装完成主题并且按文档进行配置后，运行会报错（存在解析异常）。原因是我的博客项目没安装一些npm包，例如：hexo-renderer-pug，hexo-renderer-sass等。可能有人也会出现这样的错误。文档里可以添加一个 q&a避免这种可能出现的重复问题。

主题设计得很赞！！！！！

**Comment by Haojen** [comment]
Thank you advice, you are welcome to participate in this project

**Comment by Haojen** [comment]
@lvfangren Thank you advice, you are welcome to participate in this project
