### ISSUE TITLE
修改字体

### ISSUE THREAD

**Issue by Zjrua** [Haojen/hexo-theme-Claudia#45]
能不能添加或者说明一下怎么修改主题的字体，感谢（纯小白

**Comment by Haojen** [comment]
> 能不能添加或者说明一下怎么修改主题的字体，感谢（纯小白

Sorry for now you can't  change it on config file ， but if your just want switch to another Language or rename header menu， your can read this [中文说明](https://github.com/Haojen/hexo-theme-Claudia/blob/master/README-CN.md)
