### ISSUE TITLE
problem related to inline math

### ISSUE THREAD

**Issue by seed9D** [Haojen/hexo-theme-Claudia#47]
Hi，
I like the theme, Caudia.
It is the concisest theme I have ever seen.

But, it would be better to support the in-line math
I have taken a long time solving it, but without any solution could working
I feel defeated.
Here the sample is:
 $\gamma = \cfrac{1}{n_{jm}} \sum_{x_i \in R_{i,j}}y_i - F_{m-1}(x_i)$
It works fine in my typora, but fails in Caudia

**Comment by Haojen** [comment]
@seed9D  hi seed9D, thank you report. I will fix it in next few day and thank you like it

**Comment by Haojen** [comment]
@seed9D  Did you install hexo math plugin in your blog ?

**Comment by seed9D** [comment]
@Haojen 
Yes, I have tried the solutions I could google.
Including changing the render from marked to kramed
```
$ npm uninstall hexo-renderer-marked --save
$ npm install hexo-renderer-kramed --save
```
and try these two  latex render 
* hexo-math 
* hexo-renderer-mathjax

**Comment by Haojen** [comment]
@seed9D  Good news, It worked! First you don't need change `hexo-renderer-marked`, just only install `hexo-math`, and then use `{% mathjax CONTENT  endmathjax%}`

example:
```
{% mathjax %}

$\gamma = \cfrac{1}{n_{jm}} \sum_{x_i \in R_{i,j}}y_i - F_{m-1}(x_i)$

{% endmathjax %}
```

[My mathjax test demo](https://haojen.github.io/Claudia-theme-blog/2018/02/12/hexo-theme-cutie-v2-tutorial/#Math-Test) 
Here is [My blog config ](https://github.com/Haojen/Claudia-theme-blog)

Check doc see more details and config [hexo-math](https://github.com/hexojs/hexo-math)
