### ISSUE TITLE
css文件找不到，hexo生成的scss文件

### ISSUE THREAD

**Issue by WeekiXu** [Haojen/hexo-theme-Claudia#48]
css文件找不到，hexo生成的scss文件
style/base.scss
style/theme.scss
页面请求的
/style/base.css
/style/helper.css

**Comment by Haojen** [comment]
@WeekiXu Make sure you have install `hexo-renderer-sass`, More install details please check [README](https://github.com/Haojen/hexo-theme-Claudia#install-depend)

**Comment by WeekiXu** [comment]
> @WeekiXu Make sure you have install `hexo-renderer-sass`, More install details please check [README](https://github.com/Haojen/hexo-theme-Claudia#install-depend)

原来是 npm install 一直失败，重新更换了nodejs版本到最新稳定版安装成功了。
谢谢！
