### ISSUE TITLE
关于博文封面图配置

### ISSUE THREAD

**Issue by ChildeSun** [Haojen/hexo-theme-Claudia#5]
您好，本人初识hexo。不太清楚您的claudia主题如何配置博文封面图，仅是看到修改img属性。不是很清楚在哪里修改，能麻烦您详细说明一下吗。O(∩_∩)O谢谢。

**Comment by AvalonGwenda** [comment]
同问，这里的img是在哪个文件下的？

**Comment by ZhuPan2016** [comment]
同问 : )

**Comment by zyczzh** [comment]
博客文章封面不是跟着你的post的markdon的图片走的吗？

**Comment by zyczzh** [comment]
具体应该看_partial里面的post.ejs文件，最下面有写“获取第一张图, 用以当封面背景图～”要改也是这里改，不过我会改。。。就没个post加个图片呗～嘻嘻

**Comment by ChildeSun** [comment]
懂了，谢谢。

**Comment by confiwent** [comment]
正确的方法是将封面图放在正文中，然后改为![](,"post-cover")就好了

**Comment by confiwent** [comment]
正确的方法是将背景图放在正文中，然后改成`![](,"post-cover")`就好了
