### ISSUE TITLE
请问如何修改手机端左右两侧的边距？

### ISSUE THREAD

**Issue by NonEvent** [Haojen/hexo-theme-Claudia#50]

**Comment by Haojen** [comment]
@NonEvent  Could you tell me about more detail info, And why you need adjust left and right margin?

**Comment by NonEvent** [comment]
> @NonEvent Could you tell me about more detail info, A
![Uploading WechatIMG92.jpeg…]()
nd why you need adjust left and right margin?

**Comment by NonEvent** [comment]
> @NonEvent Could you tell me about more detail info, And why you need adjust left and right margin?

![WechatIMG92](https://user-images.githubusercontent.com/25746215/106380698-0f4d7480-63ef-11eb-9ea4-e798d7d0aff6.jpeg)
点入正文之后两侧的边距有点窄。

**Comment by Haojen** [comment]
@NonEvent  已修复，感谢反馈
