### ISSUE TITLE
博客封面图片设置

### ISSUE THREAD

**Issue by Febeoro** [Haojen/hexo-theme-Claudia#52]
你好，请问博客封面设置的字段名称？可否给一下可用的相关的Front-matter？

**Comment by Febeoro** [comment]
很奇怪，本地推送有问题，但是推送到Git上网站显示是好的

**Comment by Haojen** [comment]
@Febeoro  Just post content have image, the first image will be set cover image automatically，you don't need any Front-matter

**Comment by Febeoro** [comment]
哇，明白啦，感谢！
