### ISSUE TITLE
文章中代码块出现变形

### ISSUE THREAD

**Issue by NightmareRevisited** [Haojen/hexo-theme-Claudia#53]
![image](https://user-images.githubusercontent.com/34007792/108294769-72058500-71d1-11eb-90a6-a94840a3e62b.png)

使用```在md中插入代码块，hexo g生成的html界面代码块被处理为居中样式，且代码块字体大小不一，完全无法阅读。

**Comment by Haojen** [comment]
@NightmareRevisited  Make sure you do this: [Config code highlighting](https://github.com/Haojen/hexo-theme-Claudia#code-highlighting)

**Comment by NightmareRevisited** [comment]
Thx,problem resolved after hexo default highlight is diabled
