### ISSUE TITLE
请求添加Valine评论系统支持

### ISSUE THREAD

**Issue by declan-haojin** [Haojen/hexo-theme-Claudia#54]
**Is your feature request related to a problem? Please describe.**
主题真的好棒！现在想从其他主题迁移过来但是之前的评论系统用的是valine……

**Describe the solution you'd like**
恳请大佬支持一下Valine https://valine.js.org
另外我觉得valine的优点就是不需要github或者其他第三方登录，评论可以更快捷一点

**Describe alternatives you've considered**
None

**Additional context**
再次感谢大佬开源这么棒的主题！

**Comment by Haojen** [comment]
@declan-haojin Thank you feedback, I'm glad you like it.  this Valine comment system come soon

**Comment by Haojen** [comment]
@declan-haojin  Valine has been supported,  enjoy
