### ISSUE TITLE
关于适配手机端问题，代码块问题，文章省略字数问题

### ISSUE THREAD

**Issue by sky-max-hub** [Haojen/hexo-theme-Claudia#55]
非常感谢作者做出一款如此好看的主题，整体的风格很舒服和简洁。但是有些地方希望作者可以改进一下。

代码块问题：希望能增加一键复制代码块功能，并且希望可以修改原有的代码块样式，原有的样式在谷歌浏览器上总觉得有点粗糙（个人感觉）
![图片](https://user-images.githubusercontent.com/58804729/108967047-f9fbfb00-76b9-11eb-9d7d-5eb6ba931540.png)
例如可以这样
![图片](https://user-images.githubusercontent.com/58804729/108967226-30397a80-76ba-11eb-97d2-a5a982c57fdf.png)

手机端适配问题：切换为手机端时，发现右侧的功能都隐藏了，比如文章目录功能和个人简介功能，希望手机能增加开启是否隐藏按钮
![图片](https://user-images.githubusercontent.com/58804729/108967554-a2aa5a80-76ba-11eb-909e-22fa66e4ffa3.png)
例如可以这样
![图片](https://user-images.githubusercontent.com/58804729/108967676-c5d50a00-76ba-11eb-80bd-46358f959f3e.png)

文章字数省略问题：希望可以自己设置，默认的字数省略有点太多了。在手机端显示不太好看。
![图片](https://user-images.githubusercontent.com/58804729/108968012-2ebc8200-76bb-11eb-8ab3-ae9eb0e37b51.png)

**Comment by Haojen** [comment]
@sky-max-hub 感谢喜欢以及如此详细的反馈，后面更新会考虑这块的调整，再次感谢。

**Comment by Haojen** [comment]
@sky-max-hub 补充一句，实际上有关自定义字数省略上，可以通过在文中增加 ``` <!-- more --> ``` 的形式进行截断，详情可以参考[这篇文章](https://www.jianshu.com/p/78c218f9d1e7)
