### ISSUE TITLE
一些希望增加的东西

### ISSUE THREAD

**Issue by Nambers** [Haojen/hexo-theme-Claudia#58]
这个theme整体都挺不错的，不过
1. 希望支持像链接图片一样链接博文，如`![x](/image/xx.jpg)`这个是图片
然后希望可以用这种`[x](/xxx.md)`来链接一个在_post目录下的博客，不过这个可能有点难
2. 然后好像页面会出现一会中文一会英文的情况，就右上角的工具栏
3. 字数统计
- [x] 希望增加disqus评论支持
- [x] 博文的head里的meta description为博客的简介(即前面的那部分)以获得更好的seo，并在google分析不启用的情况下删除那部分代码
- [x] 在处理代码段前先转义，否则可能出现错误

**Comment by Nambers** [comment]
https://github.com/Haojen/hexo-theme-Claudia/pull/59

**Comment by Nambers** [comment]
#62

**Comment by Nambers** [comment]
@Haojen 过下PR? 🐟

**Comment by Nambers** [comment]
然后其实第一项我是比较想解决的，但是目前还没时间去琢磨

**Comment by Haojen** [comment]
> @Haojen 过下PR? 🐟

晚些时候看看，最近有点忙 😂

**Comment by Nambers** [comment]
> > @Haojen 过下PR? 🐟
> 
> 晚些时候看看，最近有点忙 😂

ok
