### ISSUE TITLE
请求增加DaoVoice功能

### ISSUE THREAD

**Issue by F-ZhaoYang** [Haojen/hexo-theme-Claudia#60]
请求增加DaoVoice插件，可以与读者实时交互，比较知名的主题都可以方便添加
http://guide.daocloud.io/daovoice/daovoice-9151028.html
https://hanhanhanxu.github.io/2019/05/13/DaoVoice/

**Comment by Haojen** [comment]
@F-ZhaoYang  这个网站的整体的风格更合适个人博客类，与读者实时交互的这种感觉用处不是很大，倒是很多偏向商业宣传类的网站需要，因此出于上述原因暂时不考虑添加，感谢建议
