### ISSUE TITLE
主页下方添加备案信息

### ISSUE THREAD

**Issue by xiao-ming9** [Haojen/hexo-theme-Claudia#61]
您好，非常高兴发现了这个好看的主题。在配置的时候遇到一个问题，就是需要在主页下方显示备案链接，请问这个需要怎么做呢？

**Comment by Haojen** [comment]
@xiao-ming9 https://github.com/Haojen/hexo-theme-Claudia#users-profile  ```footnotes```

**Comment by xiao-ming9** [comment]
使用 footnotes 似乎只能够显示填写的字符串，没办法显示链接：
![image](https://user-images.githubusercontent.com/38147977/112597801-95fb5c80-8e48-11eb-9faa-5d932f2c91ed.png)

![image](https://user-images.githubusercontent.com/38147977/112597203-c8588a00-8e47-11eb-9ae1-ef23bbee6499.png)

**Comment by Haojen** [comment]
> @Haojen 感谢回复，使用 footnotes 之前就已经尝试过，但是似乎只能够显示填写的字符串，没办法显示链接：
> ![image](https://user-images.githubusercontent.com/38147977/112597801-95fb5c80-8e48-11eb-9faa-5d932f2c91ed.png)
> 
> ![image](https://user-images.githubusercontent.com/38147977/112597203-c8588a00-8e47-11eb-9ae1-ef23bbee6499.png)

已修复，请拉取最新的代码试试
