### ISSUE TITLE
友情链接

### ISSUE THREAD

**Issue by Nambers** [Haojen/hexo-theme-Claudia#64]
能不能加个放友情链接的侧边栏
![image](https://user-images.githubusercontent.com/35139537/115020573-5971cc80-9eed-11eb-88b7-e7d3f861447f.png)
比如这种(在别的博客截的

**Comment by Nambers** [comment]
https://github.com/Haojen/hexo-theme-Claudia/pull/62#issuecomment-826084125

**Comment by Nambers** [comment]
> 请问目前是否可以在侧栏支持友链呢？我看源代码的widgets里面还没有更新？

这个仓库一年多没维护了，可能作者有点事，建议自己写或者换主题

**Comment by jackfromeast** [comment]
感谢回复～看到您#62的pr，好像已经实现该功能，可否直接参照该commit部分代码呢？

**Comment by Nambers** [comment]
> 感谢回复～看到您#62的pr，好像已经实现该功能，可否直接参照该commit部分代码呢？

嗯
