### ISSUE TITLE
如果能结合hexo-theme-icarus的功能，那就太棒了！

### ISSUE THREAD

**Issue by GanZhiXiong** [Haojen/hexo-theme-Claudia#67]
大佬如果能把 [hexo-theme-icarus](https://github.com/ppoffice/hexo-theme-icarus) 的功能集成进来，或者给hexo-theme-icarus提一个黑暗模式的PR，那就太好了！

hexo-theme-icarus的功能、布局、配色、MarkDown支持效果都很好，唯一就是没有黑暗模式。
下面我列举几项对比吧（看图片比较）：
- 搜索
![image](https://user-images.githubusercontent.com/27394631/119256961-c1ef5000-bbf5-11eb-9443-1decd7b9f27b.png)

![image](https://user-images.githubusercontent.com/27394631/119256981-d7647a00-bbf5-11eb-97cd-71503d6a3520.png)

- 代码
![image](https://user-images.githubusercontent.com/27394631/119257018-01b63780-bbf6-11eb-90fb-c94b0d214418.png)

![image](https://user-images.githubusercontent.com/27394631/119257027-07ac1880-bbf6-11eb-9376-33d67aefefb0.png)

**Comment by Haojen** [comment]
@GanZhiXiong 给 hexo-theme-icarus 开发黑暗模式的时间成本太高了，不介意的话你可以列一个功能列表，后面我时间允许的话会添加上

**Comment by GanZhiXiong** [comment]
或者你可以防 https://ppoffice.github.io/hexo-theme-icarus/uncategorized/cyberpunk-theme-variant/ 做，我目前在用hexo-theme-icarus的cyberpunk主题，这个主题还不错。

等我先把我的博客弄完整了，我来列个功能列表。

**Comment by Haojen** [comment]
@GanZhiXiong 我先关掉，等你有功能列表了再随时打开就行
