### ISSUE TITLE
新手遇到的 bug

### ISSUE THREAD

**Issue by gitwenz** [Haojen/hexo-theme-Claudia#69]
您好我是新手
對於 hello word 文檔格式錯誤和 cover photo 無法在內文顯示的錯誤沒有頭緒
請問是安裝過程有忽略什麼嗎?

**Comment by wenchuanz** [comment]
主頁是正常的
![image](https://user-images.githubusercontent.com/34442237/130361360-5ccd97e9-107f-4c00-afa5-3c14189e4e93.png)

**Comment by Haojen** [comment]
> 您好我是新手
> 對於 hello word 文檔格式錯誤和 cover photo 無法在內文顯示的錯誤沒有頭緒
> 請問是安裝過程有忽略什麼嗎?

如果首頁展示正常，那一般是圖片路徑或者內容書寫的格式有兼容性問題，建議你把自己的博客文章先拿掉，只將 hexo 模板內容放進去看是否正常。

**Comment by gitwenz** [comment]
感謝大神
我使用您 Demo 的配置就解決了
應該是路徑沒設定好
