### ISSUE TITLE
Math support

### ISSUE THREAD

**Issue by sigempty** [Haojen/hexo-theme-Claudia#70]
按照 README 的方式安装了 hexo-renderer-mathjax，并且在文章前面设置 mathjax: true 了，但数学公式并没有解析成功。html 的文件里也没看到 mathtex 相关的转换。

按照网上的 blogs 尝试了各种办法，包括像 hexo-renderer-kramed 之类的安装和配置，但也都没有成功。。

想请问一下这个主题如果需要支持数学公式需要做什么特殊的设置吗？多谢！

**Comment by Haojen** [comment]
Make sure you have execute hexo g and clean, after retry

**Comment by sigempty** [comment]
Thanks for your soon reply. I have tried the hexo clean && hexo g before but it does not work.
I am new to front-end so I don't know why... So I just google and try the configuration/dependency alternatives one by one and I finally find this combination works:

install pandoc with the latest version. 
npm install hexo-renderer-mathjax
npm install hexo-renderer-pandoc
npm install hexo-filter-mathjax
and edit my _config.yml to enable math.

For me, I think this issue can be closed? Thanks.

> Make sure you have execute hexo g and clean, after retry

**Comment by Haojen** [comment]
@sigempty 👍
