### ISSUE TITLE
Menu titles for new pages are always lowercase

### ISSUE THREAD

**Issue by markusmoenig** [Haojen/hexo-theme-Claudia#71]
Hi

sorry this maybe a noob question.

But the menu items for new pages created with hexo page "NAME" are always displayed lowercase on the generated page, I would like to have custom menu item cases, like "ShaderMania". How to ?

Thanks!

**Comment by Dr-S1x17** [comment]
Hi bro,I make the same question and I find the way to solve it.
First,find the layout folder under the theme. open the widget folder and open widget-header.pug(this file).
U can find the tolowercase function.delete it and U find you can make the menu titles keep that U set.

**Comment by Haojen** [comment]
@markusmoenig @Dr-S1x17  thanks guys feedback, next version I will change to user input default , not force Uppercase
