### ISSUE TITLE
在嵌入代码块时，代码里面的数字会被加上number样式类名，导致代码里面的数字样式出问题

### ISSUE THREAD

**Issue by xiaoyangjia1** [Haojen/hexo-theme-Claudia#75]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Haojen** [comment]
[hexo-renderer-dartsass](https://github.com/Haojen/hexo-theme-Claudia#code-highlighting)
