### ISSUE TITLE
How to add a new icon

### ISSUE THREAD

**Issue by ZE3kr** [Haojen/hexo-theme-Claudia#78]
Hi, I am customizing this theme. I'd like to know if there is an easy to add an icon to the fonts. I notice the font files are generated by iconfont. Could you please the icons you are using so I can create new font files based on that to add new icon

**Comment by Haojen** [comment]
@ZE3kr Thank you for the feedback, I'll think about it. if I'll let you know here when it's added

**Comment by Haojen** [comment]
```
# Page icon
favicon: img/favicon.ico
```

Seed README:https://github.com/Haojen/hexo-theme-Claudia#users-profile
