### ISSUE TITLE
锚点不跳转问题可解否?

### ISSUE THREAD

**Issue by WizardMerlin** [Haojen/hexo-theme-Claudia#8]
首先感谢一下大神的模板claudia. 唯简唯美. 可是玩下来问题还是有一点儿的, 我分条陈述一下, 本条issue想请大神解决一下 `锚点不跳转` 问题.
(我试了一上午, 貌似真的不行)

thks in advanced.

**Comment by Haojen** [comment]
感谢反馈，问题已修复
