### ISSUE TITLE
我按照教程，得到了这样的局面

### ISSUE THREAD

**Issue by Parsifa1** [Haojen/hexo-theme-Claudia#81]
![question](https://s2.loli.net/2022/08/02/HWeVjT1LvqSEBnK.png)

**Comment by Haojen** [comment]
@Parsifa1 感谢使用，看截图应该是部署出了问题，并非 bug 。建议检查部署相关的流程和安装依赖

**Comment by Parsifa1** [comment]
抱歉麻烦了

**Comment by Haojen** [comment]
@Parsifa1 客气，祝一切顺利
