### ISSUE TITLE
希望能够增加如友链等其他额外页面

### ISSUE THREAD

**Issue by Parsifa1** [Haojen/hexo-theme-Claudia#82]
虽然手动添加也可以，但好像适配并不好awa
如 https://www.aldric.ml/links 所示
两个div容器排列不正常
我在离线调试的时候没有出现
（当然也可能是我自己操作的问题
麻烦啦(●'◡'●)

**Comment by Haojen** [comment]
收到，下个版本安排上

**Comment by Haojen** [comment]
@Parsifa1 已添加，使用方法见 Readme
