### ISSUE TITLE
Add the new feature for pictures zooming in&out

### ISSUE THREAD

**Issue by jackfromeast** [Haojen/hexo-theme-Claudia#84]
Hi, I found that Claudia is still unable to zoom in on pictures in the blog, which is not that user-friendly.

I would like to help add this feature by introducing `fancybox` to wrap the images. 

**If the feature makes sense to you, I could help to work around it and submit a pull request. Please let me know whether I am welcome to add this feature to Claudia!**

By the way, I am a super fan of your hexo theme! Appreciate your work so much!

**Comment by Haojen** [comment]
@jackfromeast Good to hear, you can always add new feature to this project, thank you make Claudia do better. sorry I'm repley so late.
