### ISSUE TITLE
代码块未能正常渲染

### ISSUE THREAD

**Issue by 1949hacker** [Haojen/hexo-theme-Claudia#88]
我的代码块没有正确渲染
![image](https://user-images.githubusercontent.com/67054131/202570305-19bfa1f0-9736-419e-965c-71b5e942425d.png)

**Comment by Haojen** [comment]
@1949hacker Disable the default hexo highlight configuration(modify your _config.yml in root directory of hexo), and then run hexo clean to delete cache  https://github.com/Haojen/hexo-theme-Claudia#code-highlighting
