### ISSUE TITLE
能够在下一个版本中提供归档布局?

### ISSUE THREAD

**Issue by WizardMerlin** [Haojen/hexo-theme-Claudia#9]
尝试了一下在menu中设置归档(archives)但是效果不太好.

本着简单, 优雅的原则, 大神能否在下个版本中fix&提供归档的layout呢?

大致页面效果是:(当然以您的标准为主):
2017年
 * ariticle1 时间
 * article2 时间
2016年
 * article1 时间
 * article2 时间

**Comment by Haojen** [comment]
@WizardMerlin  已添加
